name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Enviroment the action must be run on'
        type: enviroment
        required: true
        default: Production
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "📣 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "The repository  ${{ github.repository }} containts the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    if: 
    steps:
      - run: echo "Testing..."
