name: Reuse
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@erik-burigo'
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo "Time is ${{ needs.call-workflow.current-time }}"
    
